image: amazonlinux:2

stages:
  - init
  - build

before_script:
  - yum install -y unzip
  - curl -o packer.zip https://releases.hashicorp.com/packer/1.6.6/packer_1.6.6_linux_amd64.zip
  - unzip packer.zip
  - chmod +x packer
  - mv packer /usr/local/bin/
  - rm -rf packer.zip
  
  - if ! command -v aws &> /dev/null; then
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip";
      unzip awscliv2.zip;
      ./aws/install -i /usr/local/bin -b /usr/local/bin;
    fi 
  - if [[ "$ENVIRONMENT" == "DEV" ]]; then
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
      - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV
    elif [[ "$ENVIRONMENT" == "PROD" ]]; then
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
      - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD
    else
      echo "enviroment not found!..."
    fi     


init:
 stage: init 
 script:
   - mkdir -p ./.packer.d/plugings/
   - packer init aws-ami-prk.hcl 
 artifacts:
    paths: 
        - ./.packer.d/plugins/


build:
  stage: build
  script:
    - packer validate aws-ami-prk.hcl
    - packer build aws-ami-prk.hcl 
  dependencies:
    - init
  only:
     - main
  environment:
    name: $ENVIRONMENT  