
image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_BUIDKIT: 1
  IMAGE_NAME: joni/openproject
  IMAGE_TAG: latest
  REGISTRY: docker.io

stages:
  - build
  - push

before_script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   #- apk add --no-cache curl
   #- curl -fsSL https://get.docker.com | sh

build:
  stage: build
  script:
    - docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
  only:
    - main

push:
  stage: push    
  script:
    - docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
   - main
